---
# Source: doc-controller/templates/rbac.yaml
# Scoped service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bto-controller
  namespace: aruna-prod
  labels:
    app: bto-controller
    app.kubernetes.io/name: bto-controller
    app.kubernetes.io/version: "0.1.0"
automountServiceAccountToken: true
---
# Source: doc-controller/templates/rbac.yaml
# Access for the service account
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bto-controller
rules:
  - apiGroups: ["aruna-storage.org"]
    resources: ["bucketcert", "bucketcert/status"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateway"]
    verbs: ["get", "list", "watch", "patch"]
---
# Source: doc-controller/templates/rbac.yaml
# Binding the role to the account
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bto-controller
subjects:
- kind: ServiceAccount
  namespace: aruna-prod
  name: bto-controller
roleRef:
  kind: ClusterRole
  name: bto-controller
  apiGroup: rbac.authorization.k8s.io
---
# Source: doc-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bto-controller
  namespace: aruna-prod
  labels:
    app: bto-controller
    app.kubernetes.io/name: bto-controller
    app.kubernetes.io/version: "0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bto-controller
  template:
    metadata:
      labels:
        app: bto-controller
      annotations:
        kubectl.kubernetes.io/default-container: bto-controller
    spec:
      serviceAccountName: bto-controller
      securityContext:
        {}
      containers:
      - name: bto-controller
        image: "harbor.computational.bio.uni-giessen.de/aruna/s3-bucket-tls-manager:latest"
        imagePullPolicy: IfNotPresent
        securityContext:
          {}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 100Mi
